Hireforce/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Job__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Applied</fullName>
                </value>
                <value>
                    <fullName>Initial Screening Done</fullName>
                </value>
                <value>
                    <fullName>Interview Scheduled</fullName>
                </value>
                <value>
                    <fullName>Under consideration</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Offer Sent</fullName>
                </value>
                <value>
                    <fullName>Offer Accepted</fullName>
                </value>
                <value>
                    <fullName>Hired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Applicant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Hireforce/objects/Hiring_Event__c.object
<CustomObject>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>End_Time</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Event_Date__c</fullName>
        <label>Event Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Organizer_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Organizer Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Hiring Events Managed by Me</relationshipLabel>
        <relationshipName>Hiring_Events_Managed_by_Me</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Start_Time</valueSetName>
        </valueSet>
    </fields>
    <label>Hiring Event</label>
    <nameField>
        <label>Hiring Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hiring Event</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Hireforce/objects/Interview__c.object
<CustomObject>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>End_Time</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hiring_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hiring Event</label>
        <referenceTo>Hiring_Event__c</referenceTo>
        <relationshipLabel>Interviews</relationshipLabel>
        <relationshipName>Interviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Interviewer</label>
        <referenceTo>Interviewer__c</referenceTo>
        <relationshipLabel>Interviews</relationshipLabel>
        <relationshipName>Interviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Start_Time</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Invite Sent</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>No Show</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Interview</label>
    <nameField>
        <label>Interview Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Hireforce/objects/Interviewer__c.object
<CustomObject>
    <fields>
        <fullName>Available_Slots__c</fullName>
        <label>Available Slots</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>8:00 AM - 9:00 AM</fullName>
                </value>
                <value>
                    <fullName>9:00 AM - 10:00 AM</fullName>
                </value>
                <value>
                    <fullName>10:00 AM - 11:00 AM</fullName>
                </value>
                <value>
                    <fullName>11:00 AM - 12:00 PM</fullName>
                </value>
                <value>
                    <fullName>12:00 PM - 1:00 PM</fullName>
                </value>
                <value>
                    <fullName>1:00 PM - 2:00 PM</fullName>
                </value>
                <value>
                    <fullName>2:00 PM - 3:00 PM</fullName>
                </value>
                <value>
                    <fullName>3:00 PM - 4:00 PM</fullName>
                </value>
                <value>
                    <fullName>4:00 PM - 5:00 PM</fullName>
                </value>
                <value>
                    <fullName>5:00 PM - 6:00 PM</fullName>
                </value>
                <value>
                    <fullName>6:00 PM - 7:00 PM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Employee</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>My Interviewing Profile</relationshipLabel>
        <relationshipName>My_Interviewing_Profile</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hiring_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hiring Event</label>
        <referenceTo>Hiring_Event__c</referenceTo>
        <relationshipLabel>Interviewers</relationshipLabel>
        <relationshipName>Interviewers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hiring_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hiring Manager</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Interviewers Managed by Me</relationshipLabel>
        <relationshipName>Interviewers_Managed_by_Me</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interviewing_Rounds__c</fullName>
        <inlineHelpText>Please select the rounds which are assessed by this interviewer</inlineHelpText>
        <label>Interviewing Rounds</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Technical Interview - Initial</fullName>
                </value>
                <value>
                    <fullName>Technical Interview - Advanced</fullName>
                </value>
                <value>
                    <fullName>Phone Interview</fullName>
                </value>
                <value>
                    <fullName>HR Interview</fullName>
                </value>
                <value>
                    <fullName>Behavioural Interview</fullName>
                </value>
                <value>
                    <fullName>Panel Interview</fullName>
                </value>
                <value>
                    <fullName>Case Study Interview</fullName>
                </value>
                <value>
                    <fullName>Coding Challenge</fullName>
                </value>
                <value>
                    <fullName>Aptitude Test</fullName>
                </value>
                <value>
                    <fullName>Group Discussion</fullName>
                </value>
                <value>
                    <fullName>Final Interview</fullName>
                </value>
                <value>
                    <fullName>On-site Interview</fullName>
                </value>
                <value>
                    <fullName>Managerial Interview</fullName>
                </value>
                <value>
                    <fullName>Executive Interview</fullName>
                </value>
                <value>
                    <fullName>Offer Discussion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Interviewer</label>
    <nameField>
        <label>Interviewer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interviewers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Hireforce/objects/Job__c.object
<CustomObject>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Auto_publish_after_approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto publish after approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Employment_Status__c</fullName>
        <label>Employment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Filled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hiring_Manger__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hiring Manger</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Jobs Managed by Me</relationshipLabel>
        <relationshipName>Jobs_Managed_by_Me</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Status__c</fullName>
        <label>Job Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Ready to be Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Sent back for Correction</fullName>
                </value>
                <value>
                    <fullName>Ready to be Published</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Hireforce/objects/Skill_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Required_for__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job Requirement</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Required Skills</relationshipLabel>
        <relationshipName>Required_Skills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Skill__c</fullName>
        <label>Skill</label>
        <referenceTo>Skill__c</referenceTo>
        <relationshipLabel>Skill Entries</relationshipLabel>
        <relationshipName>Skill_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Skill Entry</label>
    <nameField>
        <displayFormat>SK-{0000}</displayFormat>
        <label>Skill Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skill Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Hireforce/globalValueSets/End_Time.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>9:00 AM</fullName>
    </customValue>
    <customValue>
        <fullName>10:00 AM</fullName>
    </customValue>
    <customValue>
        <fullName>11:00 AM</fullName>
    </customValue>
    <customValue>
        <fullName>12:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>1:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>2:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>3:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>4:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>5:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>6:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>7:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>8:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>9:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>8:30 PM</fullName>
        <isActive>false</isActive>
        <label>8:30 PM</label>
    </customValue>
    <customValue>
        <fullName>7:30 PM</fullName>
        <isActive>false</isActive>
        <label>7:30 PM</label>
    </customValue>
    <customValue>
        <fullName>6:30 PM</fullName>
        <isActive>false</isActive>
        <label>6:30 PM</label>
    </customValue>
    <customValue>
        <fullName>5:30 PM</fullName>
        <isActive>false</isActive>
        <label>5:30 PM</label>
    </customValue>
    <customValue>
        <fullName>4:30 PM</fullName>
        <isActive>false</isActive>
        <label>4:30 PM</label>
    </customValue>
    <customValue>
        <fullName>3:30 PM</fullName>
        <isActive>false</isActive>
        <label>3:30 PM</label>
    </customValue>
    <customValue>
        <fullName>2:30 PM</fullName>
        <isActive>false</isActive>
        <label>2:30 PM</label>
    </customValue>
    <customValue>
        <fullName>1:30 PM</fullName>
        <isActive>false</isActive>
        <label>1:30 PM</label>
    </customValue>
    <customValue>
        <fullName>12:30 PM</fullName>
        <isActive>false</isActive>
        <label>12:30 PM</label>
    </customValue>
    <customValue>
        <fullName>11:30 AM</fullName>
        <isActive>false</isActive>
        <label>11:30 AM</label>
    </customValue>
    <customValue>
        <fullName>10:30 AM</fullName>
        <isActive>false</isActive>
        <label>10:30 AM</label>
    </customValue>
    <customValue>
        <fullName>9:30 AM</fullName>
        <isActive>false</isActive>
        <label>9:30 AM</label>
    </customValue>
    <customValue>
        <fullName>8:30 AM</fullName>
        <isActive>false</isActive>
        <label>8:30 AM</label>
    </customValue>
    <masterLabel>End Time</masterLabel>
</GlobalValueSet>

Hireforce/globalValueSets/Start_Time.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>8:00 AM</fullName>
    </customValue>
    <customValue>
        <fullName>9:00 AM</fullName>
    </customValue>
    <customValue>
        <fullName>10:00 AM</fullName>
    </customValue>
    <customValue>
        <fullName>11:00 AM</fullName>
    </customValue>
    <customValue>
        <fullName>12:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>1:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>2:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>3:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>4:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>5:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>6:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>7:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>8:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>8:30 PM</fullName>
        <isActive>false</isActive>
        <label>8:30 PM</label>
    </customValue>
    <customValue>
        <fullName>7:30 PM</fullName>
        <isActive>false</isActive>
        <label>7:30 PM</label>
    </customValue>
    <customValue>
        <fullName>6:30 PM</fullName>
        <isActive>false</isActive>
        <label>6:30 PM</label>
    </customValue>
    <customValue>
        <fullName>5:30 PM</fullName>
        <isActive>false</isActive>
        <label>5:30 PM</label>
    </customValue>
    <customValue>
        <fullName>4:30 PM</fullName>
        <isActive>false</isActive>
        <label>4:30 PM</label>
    </customValue>
    <customValue>
        <fullName>3:30 PM</fullName>
        <isActive>false</isActive>
        <label>3:30 PM</label>
    </customValue>
    <customValue>
        <fullName>2:30 PM</fullName>
        <isActive>false</isActive>
        <label>2:30 PM</label>
    </customValue>
    <customValue>
        <fullName>1:30 PM</fullName>
        <isActive>false</isActive>
        <label>1:30 PM</label>
    </customValue>
    <customValue>
        <fullName>12:30 PM</fullName>
        <isActive>false</isActive>
        <label>12:30 PM</label>
    </customValue>
    <customValue>
        <fullName>11:30 AM</fullName>
        <isActive>false</isActive>
        <label>11:30 AM</label>
    </customValue>
    <customValue>
        <fullName>10:30 AM</fullName>
        <isActive>false</isActive>
        <label>10:30 AM</label>
    </customValue>
    <customValue>
        <fullName>9:30 AM</fullName>
        <isActive>false</isActive>
        <label>9:30 AM</label>
    </customValue>
    <customValue>
        <fullName>8:30 AM</fullName>
        <isActive>false</isActive>
        <label>8:30 AM</label>
    </customValue>
    <masterLabel>Start Time</masterLabel>
</GlobalValueSet>

Hireforce/classes/InterviewSchedulerControllerTest.cls
@isTest
public class InterviewSchedulerControllerTest {

    @testSetup static void setup() {
        // Create common test records
        Skill__c skill = new Skill__c(Name='Code Analysis');
        insert skill;
        List<String> title = new List<String>{'Applicant','Interviewer','Hiring manager','recruiter'};
        list<Contact> conLst = new list<Contact>();
        for(Integer i=0;i<4;i++) {
            conLst.add(new Contact(LastName = 'TestCon'+i, Title = title[i],email='test@gmail.com'));
        }
        insert conLst;
        
        Hiring_Event__c hevt = new Hiring_Event__c(Name= 'testevt',Event_Date__c =system.today(),Organizer_Name__c = conLst[2].Id,
                                                  	Start_Time__c = '8:00 AM',End_Time__c = '9:00 AM');
        insert hevt;
        
        Interviewer__c intrvw = new Interviewer__c(Name='interviwer', Employee__c =conLst[1].Id,Interviewing_Rounds__c = 'Phone Interview', 
                                                   Hiring_Manager__c= conLst[2].Id,Hiring_Event__c=hevt.id,Available_Slots__c='9:00 AM - 10:00 AM');
        insert intrvw;  
        
        Job__c jb = new Job__c(name='job',Approver__c = UserInfo.getUserId(),Hiring_Manger__c = conLst[2].Id,
                              Auto_publish_after_approval__c = true,Employment_Status__c='Open',Job_Status__c = 'Draft');
        insert jb;
        
        Skill_Entry__c se = new Skill_Entry__c(Skill__c = skill.Id,Required_for__c=jb.Id);
        insert se;
        
        jb.Job_Status__c = 'Ready to be Submitted for Approval';
        update jb;
        Set<Id> targetObjectIdSet = new Set<Id>{jb.Id};
        
        Set<Id> pIds = (new Map<Id, ProcessInstance>([SELECT Id,Status,TargetObjectId 
                                                              FROM ProcessInstance 
                                                              where Status='Pending' 
                                                              AND TargetObjectId in : targetObjectIdSet])).keySet();
        for(ProcessInstanceWorkitem processInstanceWorkItems:  [SELECT Id,ProcessInstanceId FROM ProcessInstanceWorkitem WHERE ProcessInstanceId in :pIds]){
            Approval.ProcessWorkitemRequest singleApprovalProcess = new Approval.ProcessWorkitemRequest();
            singleApprovalProcess.setComments('Reason here.');
            singleApprovalProcess.setAction('Approve');
            singleApprovalProcess.setNextApproverIds(new Id[] {UserInfo.getUserId()});
            singleApprovalProcess.setWorkitemId(processInstanceWorkItems.Id);
            Approval.ProcessResult result = Approval.process(singleApprovalProcess); 
        }
        
        Application__c app = new Application__c(name='jhon', Applicant_Email__c ='abc@gmail.com',Contact__c = conLst[0].id,
                                               Job__c =jb.Id,Phone_Number__c = '234567890',Recruiter__c = conLst[3].id,Status__c = 'Initial Screening Done');
        insert app;
    }
    
    @isTest 
    static void getNavigationDecisionTest() {
        Job__c jb = [Select id from Job__c limit 1];
        Hiring_Event__c hrevt = [select id from Hiring_Event__c limit 1];
        Application__c app = [select id from Application__c limit 1];
    	InterviewSchedulerController.getNavigationDecision('Job__c',jb.Id);
        InterviewSchedulerController.getNavigationDecision('Hiring_Event__c',hrevt.Id);
        InterviewSchedulerController.getNavigationDecision('Application__c',app.Id);
    }
    
    @isTest 
    static void getApplicantsListTest() {
        Job__c jb = [Select id from Job__c limit 1];
    	InterviewSchedulerController.getApplicantsList('job','job',jb.Id,'Initial Screening Done');    
    }
    
    @isTest 
    static void getFslDaywrapTest(){
        Job__c jb = [Select id from Job__c limit 1];
        Hiring_Event__c hrevt = [select id from Hiring_Event__c limit 1];
        Application__c app = [select id from Application__c limit 1];
        Interviewer__c intrvw = [select id from Interviewer__c limit 1];
        String day = String.valueOf(system.today().day());
        String mnth = String.valueOf(system.today().month());
        String yearr = String.valueOf(system.today().year());
        Interview__c interview = new Interview__c(Application__c=app.id);
        string datestr = mnth+'/'+day+'/'+yearr;
        InterviewSchedulerController.getneededPickListVals();
        InterviewSchedulerController.getInterviewSlotverified(datestr,'10',intrvw.Id,'1',interview);
        InterviewSchedulerController.intrvwWrap intvWrp = InterviewSchedulerController.getnewInterviewSent(datestr,'10',intrvw.Id,'1',interview,'job',jb.Id);
        InterviewSchedulerController.getInterviewSlotverified(datestr,'9',intrvw.Id,'3',interview);
        InterviewSchedulerController.getInterviewupdated(datestr,JSON.serialize(intvWrp),'8',intrvw.Id);
        InterviewSchedulerController.getIntrvwFeedbackUpdated(intvWrp.intrvw.Id,'Reject','text');
        InterviewSchedulerController.getIntrvwStsUpdated(intvWrp.intrvw.Id,'Confirmed');
        InterviewSchedulerController.getFslDaywrap(yearr,mnth,day,'current','job',jb.Id,'1','Test');
        InterviewSchedulerController.getFslDaywrap(yearr,mnth,day,'current','hiringevent',hrevt.Id,'1','Test');
        InterviewSchedulerController.getFslDaywrap(yearr,mnth,day,'current','application',app.Id,'1','Test');
        InterviewSchedulerController.gethr('12','AM');
        InterviewSchedulerController.gethr('1','PM');
        InterviewSchedulerController.gethr('2','PM');
        InterviewSchedulerController.gethr('3','PM');
        InterviewSchedulerController.gethr('4','PM');
        InterviewSchedulerController.gethr('5','PM');
        InterviewSchedulerController.gethr('6','PM');
        InterviewSchedulerController.gethr('7','PM');
        InterviewSchedulerController.gethr('8','PM');
        InterviewSchedulerController.gethr('9','PM');
        InterviewSchedulerController.gethr('10','PM');
        InterviewSchedulerController.gethr('11','PM');
        InterviewSchedulerController.gethr('12','PM');
    }
    
    @isTest 
    static void getFslDaywrapTest2(){
        Job__c jb = [Select id from Job__c limit 1];
        Hiring_Event__c hrevt = [select id from Hiring_Event__c limit 1];
        Application__c app = [select id from Application__c limit 1];
        Interviewer__c intrvw = [select id from Interviewer__c limit 1];
        String day = String.valueOf(system.today().day());
        String mnth = String.valueOf(system.today().month());
        String yearr = String.valueOf(system.today().year());
        Interview__c interview = new Interview__c(Application__c=app.id);
        string datestr = mnth+'/'+day+'/'+yearr;
        InterviewSchedulerController.getInterviewSlotverified(datestr,'18',intrvw.Id,'10',interview);
        //InterviewSchedulerController.getnewInterviewSent(datestr,'18',intrvw.Id,'20',interview,'job',jb.Id);
        
    }
}