Hireforce/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Applicant_Email__c</fullName>
        <label>Applicant Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recruiter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recruiter</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications Managed by Me</relationshipLabel>
        <relationshipName>Applications_Managed_by_Me</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Applicant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Hireforce/objects/Interview__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Interviews</relationshipLabel>
        <relationshipName>Interviews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>End_Time</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interview_Date__c</fullName>
        <label>Interview Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Interviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Interviewer</label>
        <referenceTo>Interviewer__c</referenceTo>
        <relationshipLabel>Interviews</relationshipLabel>
        <relationshipName>Interviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scheduled_End_Time__c</fullName>
        <label>Scheduled End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Scheduled_Start_Time__c</fullName>
        <label>Scheduled Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Start_Time</valueSetName>
        </valueSet>
    </fields>
    <label>Interview</label>
    <nameField>
        <label>Interview Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Hireforce/objects/Interviewer__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Employee</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>My Interviewing Profile</relationshipLabel>
        <relationshipName>My_Interviewing_Profile</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interviewing_Rounds__c</fullName>
        <inlineHelpText>Please select the rounds which are assessed by this interviewer</inlineHelpText>
        <label>Interviewing Rounds</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Technical Interview - Initial</fullName>
                </value>
                <value>
                    <fullName>Technical Interview - Advanced</fullName>
                </value>
                <value>
                    <fullName>Phone Interview</fullName>
                </value>
                <value>
                    <fullName>HR Interview</fullName>
                </value>
                <value>
                    <fullName>Behavioural Interview</fullName>
                </value>
                <value>
                    <fullName>Panel Interview</fullName>
                </value>
                <value>
                    <fullName>Case Study Interview</fullName>
                </value>
                <value>
                    <fullName>Coding Challenge</fullName>
                </value>
                <value>
                    <fullName>Aptitude Test</fullName>
                </value>
                <value>
                    <fullName>Group Discussion</fullName>
                </value>
                <value>
                    <fullName>Final Interview</fullName>
                </value>
                <value>
                    <fullName>On-site Interview</fullName>
                </value>
                <value>
                    <fullName>Managerial Interview</fullName>
                </value>
                <value>
                    <fullName>Executive Interview</fullName>
                </value>
                <value>
                    <fullName>Offer Discussion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Interviewer</label>
    <nameField>
        <label>Interviewer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interviewers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Hireforce/globalValueSets/End_Time.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>9:00 AM</fullName>
    </customValue>
    <customValue>
        <fullName>10:00 AM</fullName>
    </customValue>
    <customValue>
        <fullName>11:00 AM</fullName>
    </customValue>
    <customValue>
        <fullName>12:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>1:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>2:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>3:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>4:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>5:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>6:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>7:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>8:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>9:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>8:30 PM</fullName>
        <isActive>false</isActive>
        <label>8:30 PM</label>
    </customValue>
    <customValue>
        <fullName>7:30 PM</fullName>
        <isActive>false</isActive>
        <label>7:30 PM</label>
    </customValue>
    <customValue>
        <fullName>6:30 PM</fullName>
        <isActive>false</isActive>
        <label>6:30 PM</label>
    </customValue>
    <customValue>
        <fullName>5:30 PM</fullName>
        <isActive>false</isActive>
        <label>5:30 PM</label>
    </customValue>
    <customValue>
        <fullName>4:30 PM</fullName>
        <isActive>false</isActive>
        <label>4:30 PM</label>
    </customValue>
    <customValue>
        <fullName>3:30 PM</fullName>
        <isActive>false</isActive>
        <label>3:30 PM</label>
    </customValue>
    <customValue>
        <fullName>2:30 PM</fullName>
        <isActive>false</isActive>
        <label>2:30 PM</label>
    </customValue>
    <customValue>
        <fullName>1:30 PM</fullName>
        <isActive>false</isActive>
        <label>1:30 PM</label>
    </customValue>
    <customValue>
        <fullName>12:30 PM</fullName>
        <isActive>false</isActive>
        <label>12:30 PM</label>
    </customValue>
    <customValue>
        <fullName>11:30 AM</fullName>
        <isActive>false</isActive>
        <label>11:30 AM</label>
    </customValue>
    <customValue>
        <fullName>10:30 AM</fullName>
        <isActive>false</isActive>
        <label>10:30 AM</label>
    </customValue>
    <customValue>
        <fullName>9:30 AM</fullName>
        <isActive>false</isActive>
        <label>9:30 AM</label>
    </customValue>
    <customValue>
        <fullName>8:30 AM</fullName>
        <isActive>false</isActive>
        <label>8:30 AM</label>
    </customValue>
    <masterLabel>End Time</masterLabel>
</GlobalValueSet>

Hireforce/globalValueSets/Start_Time.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>8:00 AM</fullName>
    </customValue>
    <customValue>
        <fullName>9:00 AM</fullName>
    </customValue>
    <customValue>
        <fullName>10:00 AM</fullName>
    </customValue>
    <customValue>
        <fullName>11:00 AM</fullName>
    </customValue>
    <customValue>
        <fullName>12:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>1:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>2:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>3:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>4:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>5:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>6:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>7:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>8:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>8:30 PM</fullName>
        <isActive>false</isActive>
        <label>8:30 PM</label>
    </customValue>
    <customValue>
        <fullName>7:30 PM</fullName>
        <isActive>false</isActive>
        <label>7:30 PM</label>
    </customValue>
    <customValue>
        <fullName>6:30 PM</fullName>
        <isActive>false</isActive>
        <label>6:30 PM</label>
    </customValue>
    <customValue>
        <fullName>5:30 PM</fullName>
        <isActive>false</isActive>
        <label>5:30 PM</label>
    </customValue>
    <customValue>
        <fullName>4:30 PM</fullName>
        <isActive>false</isActive>
        <label>4:30 PM</label>
    </customValue>
    <customValue>
        <fullName>3:30 PM</fullName>
        <isActive>false</isActive>
        <label>3:30 PM</label>
    </customValue>
    <customValue>
        <fullName>2:30 PM</fullName>
        <isActive>false</isActive>
        <label>2:30 PM</label>
    </customValue>
    <customValue>
        <fullName>1:30 PM</fullName>
        <isActive>false</isActive>
        <label>1:30 PM</label>
    </customValue>
    <customValue>
        <fullName>12:30 PM</fullName>
        <isActive>false</isActive>
        <label>12:30 PM</label>
    </customValue>
    <customValue>
        <fullName>11:30 AM</fullName>
        <isActive>false</isActive>
        <label>11:30 AM</label>
    </customValue>
    <customValue>
        <fullName>10:30 AM</fullName>
        <isActive>false</isActive>
        <label>10:30 AM</label>
    </customValue>
    <customValue>
        <fullName>9:30 AM</fullName>
        <isActive>false</isActive>
        <label>9:30 AM</label>
    </customValue>
    <customValue>
        <fullName>8:30 AM</fullName>
        <isActive>false</isActive>
        <label>8:30 AM</label>
    </customValue>
    <masterLabel>Start Time</masterLabel>
</GlobalValueSet>

Hireforce/classes/InterviewTriggerHandlerTest.cls
@isTest
public class InterviewTriggerHandlerTest {
    
    @testSetup
    static void setup() {
        Contact userContact = new Contact(FirstName = 'Test', LastName = 'Contact');
        insert userContact;
        
        Contact interviewerContact = new Contact(FirstName = 'Interviewer', LastName = 'Contact');
        insert interviewerContact;
        
        Application__c app = new Application__c();
        app.Name = 'Test User';
        app.Applicant_Email__c = 'test@user.com';
        app.Contact__c = userContact.Id;
        app.Recruiter__c = interviewerContact.Id; 
        insert app;
    }
    
    @isTest
    static void testHandleBefore() {
        
        Application__c app= [Select id from Application__c where Name = 'Test User' LIMIT 1];
        
        
        // Test with both Start_Time__c and End_Time__c null
        Interview__c interview1 = new Interview__c();
        interview1.Application__c = app.Id;
        insert interview1;

        // Test with valid Interview_Date__c, Start_Time__c, and End_Time__c
        Interview__c interview2 = new Interview__c(
            Interview_Date__c = Date.today(),
            Start_Time__c = '8:00 AM',
            End_Time__c = '10:00 AM'
        );
        interview2.Application__c = app.Id;
        insert interview2;

        // Test with Interview_Date__c null but Start_Time__c and End_Time__c provided
        Interview__c interview3 = new Interview__c(
            Start_Time__c = '8:00 AM',
            End_Time__c = '10:00 AM'
        );
        interview3.Application__c = app.Id;
        try {
            insert interview3;
            System.assert(false, 'Expected exception due to missing Interview_Date__c');
        } catch (DmlException e) {
            System.assert(e.getMessage().contains('Please select a date for the interview'));
        }

        // Test with Interview_Date__c provided but Start_Time__c greater than End_Time__c
        Interview__c interview4 = new Interview__c(
            Interview_Date__c = Date.today(),
            Start_Time__c = '10:00 AM',
            End_Time__c = '8:30 AM'
        );
        interview4.Application__c = app.Id;
        try {
            insert interview4;
            System.assert(false, 'Expected exception due to invalid time range');
        } catch (DmlException e) {
            System.assert(e.getMessage().contains('Interview start time cannot be more than end time.'));
        }
    }

    @isTest
    static void testPopulateDateTimeOnInterview() {
        Application__c app= [Select id,Recruiter__c from Application__c where Name = 'Test User' LIMIT 1];
        
        Interviewer__c interviewer = new Interviewer__c();
        interviewer.Employee__c = app.Recruiter__c;
        interviewer.Interviewing_Rounds__c ='Behavioural Interview;Coding Challenge';
        insert interviewer;

 		Interview__c interview = new Interview__c(
            Interview_Date__c = Date.today(),
            Start_Time__c = '8:00 AM',
            End_Time__c = '10:00 AM'
        );
        interview.Application__c = app.Id;   
        interview.Interviewer__c = interviewer.Id;
        insert interview; 

        // Verify Scheduled_Start_Time__c and Scheduled_End_Time__c are populated correctly
        interview = [SELECT Scheduled_Start_Time__c, Scheduled_End_Time__c FROM Interview__c WHERE Id = :interview.Id];
        Datetime expectedStartTime = DateTime.newInstance(Date.today().year(), Date.today().month(), Date.today().day(), 8, 0, 0);
        Datetime expectedEndTime = DateTime.newInstance(Date.today().year(), Date.today().month(), Date.today().day(), 10, 0, 0);
        System.assertEquals(expectedStartTime, interview.Scheduled_Start_Time__c, 'Scheduled_Start_Time__c should be correct');
        System.assertEquals(expectedEndTime, interview.Scheduled_End_Time__c, 'Scheduled_End_Time__c should be correct');
    }
}