Hireforce/objects/Hiring_Event__c.object
<CustomObject>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>End_Time</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Event_Date__c</fullName>
        <label>Event Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Organizer_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Organizer Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Hiring Events Managed by Me</relationshipLabel>
        <relationshipName>Hiring_Events_Managed_by_Me</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Start_Time</valueSetName>
        </valueSet>
    </fields>
    <label>Hiring Event</label>
    <nameField>
        <label>Hiring Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hiring Event</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Hireforce/objects/Interviewer__c.object
<CustomObject>
    <fields>
        <fullName>Available_Slots__c</fullName>
        <label>Available Slots</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>8:00 AM - 9:00 AM</fullName>
                </value>
                <value>
                    <fullName>9:00 AM - 10:00 AM</fullName>
                </value>
                <value>
                    <fullName>10:00 AM - 11:00 AM</fullName>
                </value>
                <value>
                    <fullName>11:00 AM - 12:00 PM</fullName>
                </value>
                <value>
                    <fullName>12:00 PM - 1:00 PM</fullName>
                </value>
                <value>
                    <fullName>1:00 PM - 2:00 PM</fullName>
                </value>
                <value>
                    <fullName>2:00 PM - 3:00 PM</fullName>
                </value>
                <value>
                    <fullName>3:00 PM - 4:00 PM</fullName>
                </value>
                <value>
                    <fullName>4:00 PM - 5:00 PM</fullName>
                </value>
                <value>
                    <fullName>5:00 PM - 6:00 PM</fullName>
                </value>
                <value>
                    <fullName>6:00 PM - 7:00 PM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Employee</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>My Interviewing Profile</relationshipLabel>
        <relationshipName>My_Interviewing_Profile</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hiring_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hiring Event</label>
        <referenceTo>Hiring_Event__c</referenceTo>
        <relationshipLabel>Interviewers</relationshipLabel>
        <relationshipName>Interviewers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hiring_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hiring Manager</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Interviewers Managed by Me</relationshipLabel>
        <relationshipName>Interviewers_Managed_by_Me</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interviewing_Rounds__c</fullName>
        <inlineHelpText>Please select the rounds which are assessed by this interviewer</inlineHelpText>
        <label>Interviewing Rounds</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Technical Interview - Initial</fullName>
                </value>
                <value>
                    <fullName>Technical Interview - Advanced</fullName>
                </value>
                <value>
                    <fullName>Phone Interview</fullName>
                </value>
                <value>
                    <fullName>HR Interview</fullName>
                </value>
                <value>
                    <fullName>Behavioural Interview</fullName>
                </value>
                <value>
                    <fullName>Panel Interview</fullName>
                </value>
                <value>
                    <fullName>Case Study Interview</fullName>
                </value>
                <value>
                    <fullName>Coding Challenge</fullName>
                </value>
                <value>
                    <fullName>Aptitude Test</fullName>
                </value>
                <value>
                    <fullName>Group Discussion</fullName>
                </value>
                <value>
                    <fullName>Final Interview</fullName>
                </value>
                <value>
                    <fullName>On-site Interview</fullName>
                </value>
                <value>
                    <fullName>Managerial Interview</fullName>
                </value>
                <value>
                    <fullName>Executive Interview</fullName>
                </value>
                <value>
                    <fullName>Offer Discussion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Interviewer</label>
    <nameField>
        <label>Interviewer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interviewers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Hireforce/objects/Skill__c.object
<CustomObject>
    <label>Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Hireforce/objects/Skill_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Acquired_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Acquired By</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Acquired Skills</relationshipLabel>
        <relationshipName>Acquired_Skills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Skill__c</fullName>
        <label>Skill</label>
        <referenceTo>Skill__c</referenceTo>
        <relationshipLabel>Skill Entries</relationshipLabel>
        <relationshipName>Skill_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Skill Entry</label>
    <nameField>
        <displayFormat>SK-{0000}</displayFormat>
        <label>Skill Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skill Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Hireforce/globalValueSets/End_Time.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>9:00 AM</fullName>
    </customValue>
    <customValue>
        <fullName>10:00 AM</fullName>
    </customValue>
    <customValue>
        <fullName>11:00 AM</fullName>
    </customValue>
    <customValue>
        <fullName>12:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>1:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>2:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>3:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>4:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>5:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>6:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>7:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>8:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>9:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>8:30 PM</fullName>
        <isActive>false</isActive>
        <label>8:30 PM</label>
    </customValue>
    <customValue>
        <fullName>7:30 PM</fullName>
        <isActive>false</isActive>
        <label>7:30 PM</label>
    </customValue>
    <customValue>
        <fullName>6:30 PM</fullName>
        <isActive>false</isActive>
        <label>6:30 PM</label>
    </customValue>
    <customValue>
        <fullName>5:30 PM</fullName>
        <isActive>false</isActive>
        <label>5:30 PM</label>
    </customValue>
    <customValue>
        <fullName>4:30 PM</fullName>
        <isActive>false</isActive>
        <label>4:30 PM</label>
    </customValue>
    <customValue>
        <fullName>3:30 PM</fullName>
        <isActive>false</isActive>
        <label>3:30 PM</label>
    </customValue>
    <customValue>
        <fullName>2:30 PM</fullName>
        <isActive>false</isActive>
        <label>2:30 PM</label>
    </customValue>
    <customValue>
        <fullName>1:30 PM</fullName>
        <isActive>false</isActive>
        <label>1:30 PM</label>
    </customValue>
    <customValue>
        <fullName>12:30 PM</fullName>
        <isActive>false</isActive>
        <label>12:30 PM</label>
    </customValue>
    <customValue>
        <fullName>11:30 AM</fullName>
        <isActive>false</isActive>
        <label>11:30 AM</label>
    </customValue>
    <customValue>
        <fullName>10:30 AM</fullName>
        <isActive>false</isActive>
        <label>10:30 AM</label>
    </customValue>
    <customValue>
        <fullName>9:30 AM</fullName>
        <isActive>false</isActive>
        <label>9:30 AM</label>
    </customValue>
    <customValue>
        <fullName>8:30 AM</fullName>
        <isActive>false</isActive>
        <label>8:30 AM</label>
    </customValue>
    <masterLabel>End Time</masterLabel>
</GlobalValueSet>

Hireforce/globalValueSets/Start_Time.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>8:00 AM</fullName>
    </customValue>
    <customValue>
        <fullName>9:00 AM</fullName>
    </customValue>
    <customValue>
        <fullName>10:00 AM</fullName>
    </customValue>
    <customValue>
        <fullName>11:00 AM</fullName>
    </customValue>
    <customValue>
        <fullName>12:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>1:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>2:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>3:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>4:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>5:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>6:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>7:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>8:00 PM</fullName>
    </customValue>
    <customValue>
        <fullName>8:30 PM</fullName>
        <isActive>false</isActive>
        <label>8:30 PM</label>
    </customValue>
    <customValue>
        <fullName>7:30 PM</fullName>
        <isActive>false</isActive>
        <label>7:30 PM</label>
    </customValue>
    <customValue>
        <fullName>6:30 PM</fullName>
        <isActive>false</isActive>
        <label>6:30 PM</label>
    </customValue>
    <customValue>
        <fullName>5:30 PM</fullName>
        <isActive>false</isActive>
        <label>5:30 PM</label>
    </customValue>
    <customValue>
        <fullName>4:30 PM</fullName>
        <isActive>false</isActive>
        <label>4:30 PM</label>
    </customValue>
    <customValue>
        <fullName>3:30 PM</fullName>
        <isActive>false</isActive>
        <label>3:30 PM</label>
    </customValue>
    <customValue>
        <fullName>2:30 PM</fullName>
        <isActive>false</isActive>
        <label>2:30 PM</label>
    </customValue>
    <customValue>
        <fullName>1:30 PM</fullName>
        <isActive>false</isActive>
        <label>1:30 PM</label>
    </customValue>
    <customValue>
        <fullName>12:30 PM</fullName>
        <isActive>false</isActive>
        <label>12:30 PM</label>
    </customValue>
    <customValue>
        <fullName>11:30 AM</fullName>
        <isActive>false</isActive>
        <label>11:30 AM</label>
    </customValue>
    <customValue>
        <fullName>10:30 AM</fullName>
        <isActive>false</isActive>
        <label>10:30 AM</label>
    </customValue>
    <customValue>
        <fullName>9:30 AM</fullName>
        <isActive>false</isActive>
        <label>9:30 AM</label>
    </customValue>
    <customValue>
        <fullName>8:30 AM</fullName>
        <isActive>false</isActive>
        <label>8:30 AM</label>
    </customValue>
    <masterLabel>Start Time</masterLabel>
</GlobalValueSet>

Hireforce/classes/EntrollmentIntrviewerCntrlTest.cls
@isTest
public class EntrollmentIntrviewerCntrlTest {
	
    @testSetup 
    static void setup() {
        // Create common test records
        Skill__c skill = new Skill__c(Name='Code Analysis');
        insert skill;
        List<String> title = new List<String>{'Applicant','Interviewer','Hiring manager','recruiter'};
        list<Contact> conLst = new list<Contact>();
        for(Integer i=0;i<4;i++) {
            conLst.add(new Contact(LastName = 'TestCon'+i, Title = title[i],email='test@gmail.com'));
        }
        insert conLst;
        
        Hiring_Event__c hevt = new Hiring_Event__c(Name= 'testevt',Event_Date__c =system.today(),Organizer_Name__c = conLst[2].Id,
                                                  	Start_Time__c = '8:00 AM',End_Time__c = '9:00 AM');
        insert hevt;
        
        Interviewer__c intrvw = new Interviewer__c(Name='interviwer', Employee__c =conLst[1].Id,Interviewing_Rounds__c = 'Phone Interview', 
                                                   Hiring_Manager__c= conLst[2].Id,Available_Slots__c='9:00 AM - 10:00 AM');
        insert intrvw; 
        Skill_Entry__c se = new Skill_Entry__c(Skill__c = skill.Id,Acquired_By__c = conLst[1].Id);
        insert se;
    }
    
    @isTest 
    static void retrieveInterviewersTest() {
        Hiring_Event__c hrevt = [select id from Hiring_Event__c limit 1];
        Interviewer__c intrvw = [select id,Employee__c from Interviewer__c];
        List<String> selIds = new List<String>{intrvw.Id+'@@'+intrvw.Employee__c};
        EntrollmentIntrviewerCntrl.retrieveInterviewers('Code Analysis',hrevt.Id);
        EntrollmentIntrviewerCntrl.getInterviewersEnrolled(hrevt.Id,selIds);
    }
}