Hireforce/objects/Hiring_Event__c.object
<CustomObject>
    <fields>
        <fullName>Event_Date__c</fullName>
        <label>Event Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Hiring Event</label>
    <nameField>
        <label>Hiring Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hiring Event</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Hireforce/objects/Interviewer__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Employee</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>My Interviewing Profile</relationshipLabel>
        <relationshipName>My_Interviewing_Profile</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hiring_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hiring Event</label>
        <referenceTo>Hiring_Event__c</referenceTo>
        <relationshipLabel>Interviewers</relationshipLabel>
        <relationshipName>Interviewers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hiring_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hiring Manager</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Interviewers Managed by Me</relationshipLabel>
        <relationshipName>Interviewers_Managed_by_Me</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interviewing_Rounds__c</fullName>
        <inlineHelpText>Please select the rounds which are assessed by this interviewer</inlineHelpText>
        <label>Interviewing Rounds</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Technical Interview - Initial</fullName>
                </value>
                <value>
                    <fullName>Technical Interview - Advanced</fullName>
                </value>
                <value>
                    <fullName>Phone Interview</fullName>
                </value>
                <value>
                    <fullName>HR Interview</fullName>
                </value>
                <value>
                    <fullName>Behavioural Interview</fullName>
                </value>
                <value>
                    <fullName>Panel Interview</fullName>
                </value>
                <value>
                    <fullName>Case Study Interview</fullName>
                </value>
                <value>
                    <fullName>Coding Challenge</fullName>
                </value>
                <value>
                    <fullName>Aptitude Test</fullName>
                </value>
                <value>
                    <fullName>Group Discussion</fullName>
                </value>
                <value>
                    <fullName>Final Interview</fullName>
                </value>
                <value>
                    <fullName>On-site Interview</fullName>
                </value>
                <value>
                    <fullName>Managerial Interview</fullName>
                </value>
                <value>
                    <fullName>Executive Interview</fullName>
                </value>
                <value>
                    <fullName>Offer Discussion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Interviewer</label>
    <nameField>
        <label>Interviewer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interviewers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Hireforce/objects/Skill__c.object
<CustomObject>
    <label>Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Hireforce/objects/Skill_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Acquired_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Acquired By</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Acquired Skills</relationshipLabel>
        <relationshipName>Acquired_Skills</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Skill__c</fullName>
        <label>Skill</label>
        <referenceTo>Skill__c</referenceTo>
        <relationshipLabel>Skill Entries</relationshipLabel>
        <relationshipName>Skill_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Skill Entry</label>
    <nameField>
        <displayFormat>SK-{0000}</displayFormat>
        <label>Skill Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skill Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Hireforce/classes/EntrollmentIntrviewerCntrl.cls
public with sharing class EntrollmentIntrviewerCntrl {
    
    @AuraEnabled
    public static List<Interviewer__c> retrieveInterviewers(String serchtxt,String hringEvtId){
        date today = System.today();
        String serch = '%'+serchtxt+'%';
        String searchquery = 'select id,Name,Employee__c,Hiring_Manager__c,Hiring_Manager__r.Name,Hiring_Event__c,Interviewing_Rounds__c,Employee__r.Name from Interviewer__c';
        
        if(String.isNotEmpty(serchtxt) && !serchtxt.containsIgnoreCase('null'))
        {
            Set<String> conids = new Set<String>(); 
            for(Skill_Entry__c skill : [select id,Acquired_By__c,Skill__c from Skill_Entry__c where Skill__r.Name like :serchtxt AND Acquired_By__c != null])
            {
                conids.add(skill.Acquired_By__c);
            }
            String includeClause = '';
            List<String> intrvwngRounds = InterviewSchedulerController.getpickvls('Interviewer__c','Interviewing_Rounds__c',serchtxt);
            if(intrvwngRounds.size() > 0){
                includeClause = String.join(intrvwngRounds, ';');
            } else{
                includeClause = serchtxt;
            }
            searchquery += ' Where (Name like :serch OR Hiring_Manager__r.Name like :serch OR Employee__c IN: conids OR Interviewing_Rounds__c includes (:includeClause))';
            searchquery += ' And ((Hiring_Event__c != null AND Hiring_Event__c !=: hringEvtId AND Hiring_Event__r.Event_Date__c <: today) OR Hiring_Event__c = null) LIMIT 50';
        } else {
            searchquery += ' Where ((Hiring_Event__c != null AND Hiring_Event__c !=: hringEvtId AND Hiring_Event__r.Event_Date__c <: today) OR Hiring_Event__c = null) LIMIT 50';
        }
        
        List<Interviewer__c> searchList = Database.query(searchquery);
        return searchList;
    }
	
    @AuraEnabled
    public static String getInterviewersEnrolled(String hringEvtId,List<String> selIds){
        Hiring_Event__c hevt = [select id,Name,Event_Date__c from Hiring_Event__c where id =: hringEvtId];
        List<Interviewer__c> intvrList = new List<Interviewer__c>();
        List<Task> tList = new List<Task>(); 
        for(String selId : selIds){
            List<String> idslist = selId.split('@@');
            intvrList.add(new Interviewer__c(Id = idslist[0],Hiring_Event__c = hringEvtId));
            
            Task t = new Task();
            t.OwnerId = UserInfo.getUserId();
            t.Subject = 'Please provide details : '+hevt.Name;
            t.Status = 'Open';
            t.Priority = 'Normal';
            t.WhatId = idslist[0];
            t.WhoId = idslist[1];
            t.ActivityDate = System.today().addDays(1); 
            t.Description = 'Please open Interviewer record associated to this task and provide "Available for Hiring Event" and "Available Slots" details.';
            tList.add(t);
        }
        if(intvrList.size() > 0){
        	update intvrList;	    
        }
        if(tList.size() > 0){
        	insert tList;	    
        }
        return 'done';
    }
}